volumes:
  postgres-data:
    driver: local
  finpay-postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  kestra-data:
    driver: local

networks:
  finpay-network:
    name: finpay-network
    driver: bridge

services:
  postgres:
    image: postgres:18
    networks:
      - finpay-network
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  finpay-postgres:
    image: postgres:18
    networks:
      - finpay-network
    volumes:
      - finpay-postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: finpay
      POSTGRES_USER: finpay
      POSTGRES_PASSWORD: finpay
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  finpay-pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - finpay-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finpay.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      finpay-postgres:
        condition: service_healthy

  kestra:
    image: kestra/kestra:latest
    networks:
      - finpay-network
    pull_policy: always
    stop_grace_period: 6m
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    env_file:
      - .env_encoded
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              username: admin@kestra.io
              password: Admin1234!
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
            python:
              version: "3.11"
          url: http://localhost:8080/
          
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volumeEnabled: true
                  networkMode: finpay-network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      finpay-postgres:
        condition: service_healthy
