name: linkaja_analytics
version: "1.0.0"
config-version: 2

profile: linkaja_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets:
  - target
  - dbt_packages

models:
  linkaja_analytics:
    +tags: ["linkaja"]
    staging:
      +materialized: view
